#! /bin/bash

TOTAL_TEST_CASES=9

# see if the number of tests to replace is given
if (test $# -gt 1)
then
    echo "Only required one optional argument: number of test to replace"
    exit 1
elif (test $# -eq 1)
then
    TOTAL_TEST_CASES=$1
fi

echo "Replacing $TOTAL_TEST_CASES tests."

rm -rf test_inputs/*.bmp
mkdir -p test_inputs

for i in `seq $TOTAL_TEST_CASES`
do
    cp test_inputs.bak/BMP$i.bmp test_inputs/
done
